### ISSUE TITLE
Rollout

### ISSUE THREAD

**Issue by oxinabox** [SciML/ColPrac#1]
This is to track rolling this out across organizations,
a lot of PRs need to be made to add this to `README.md`s

for convinence here is the markdown for the badge
```markdown
[![ColPrac: Contributor's Guide on Collaborative Practices for Community Packages](https://img.shields.io/badge/ColPrac-Contributor's%20Guide-blueviolet)](https://github.com/SciML/ColPrac)
```

- [ ] JuliaCollections
- [x] SciML
- [ ] JuliaDiff
- [ ] FluxML

Feel free to add others if we also need to track them

**Comment by ChrisRackauckas** [comment]
We put it on the SciML websites. I think that's all I am going to do unless someone wants to roll out a script that opens a PR for every repo since that's... just... a lot of work.
