### ISSUE TITLE
Incompatible with `CuArray` from `CUDA.jl`

### ISSUE THREAD

**Issue by parthe** [SciML/ColPrac#25]
Right now the package does not allow kernel matrix calculations with CUDA arrays which have type CuArray
For example, the following code breaks
```julia
using KernelFunctions, CUDA
x = CUDA.randn(10, 2);
z = CUDA.randn(100, 2);
k = GaussianKernel();
K_xz = kernelmatrix(k, x, z, obsdim=1);
```

It seems to me that the code can work just as well with `CuArray` from `CUDA.jl`

Can this functionality be added. As far as I can tell, we just need to add new method with CuArray as input data type.

**Comment by chriselrod** [comment]
Did you intend to file this issue elsewhere?

**Comment by ChrisRackauckas** [comment]
lol, I'm curious to know what happened here haha
